### ISSUE TITLE
Muting

### ISSUE THREAD

**Issue by evanextreme** [RITesports/ricky#16]
Ability for moderators to give a specific role to a user. We already have the role in our server, with ID <@&269626947498278912>. 
There's a few ways we can implement this, by reworking our management system to allow for two classes of roles, one which any user can assign to themselves (our current community roles) and a mute functionality which can only be employed by our mods/community team that is assigned to members of the server. Maybe a timeout for this could be implemented too.

**Comment by rag4214** [comment]
Sorry, just getting to look at this. I think the best course of action would be to have two classes of roles. Right now bricky is at the bottom of the list and can only add stuff under him. The best course of action would be to either have a json with the roles or have 2 different text files AND have ricky at the top of the role list. The only issue with this is we would have to manually add the roles, which is not efficient. At that point it would just be a simple lookup for a role matching one in the list and seeing if they can add it.

**Comment by rag4214** [comment]
Added in #37
